FROM mcr.microsoft.com/dotnet/sdk:9.0 AS tests-runner
WORKDIR /src

COPY ["Riders/Riders.csproj", "Riders/"]
COPY ["Aplication/Aplication.csproj", "Aplication/"]
COPY ["Domain/Domain.csproj", "Domain/"]
COPY ["Infraestructure/Infraestructure.csproj", "Infraestructure/"]
COPY ["Test_Riders/Test_Riders.csproj", "Test_Riders/"]

RUN dotnet restore "Test_Riders/Test_Riders.csproj"

COPY . .
RUN dotnet build "Test_Riders/Test_Riders.csproj" -c Release --no-restore

ENTRYPOINT ["dotnet", "test", "Test_Riders/Test_Riders.csproj", "-c", "Release", "--no-build", "--logger:trx;LogFileName=test_results.trx", "--results-directory", "/testresults"]