global:
  scrape_interval: 15s
  
scrape_configs:
 
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']