global:
  scrape_interval: 15s
  
scrape_configs:
 
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']
    
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']