networks:
  monitoring:
    external: true
    name: monitoring
  production:
    external: true
    name: production

services:
   prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    labels:
      # Habilita descoberta do container
      - "traefik.enable=true"
          # Habilita a rota do traefik
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.riders.lat`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"

       # Habilita o service do traefik (Exposer a porta interna do prometheus)
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      # Habilita o middleware de segurança
      - "traefik.http.middlewares.prometheus-auth.basicauth.users=admin:$2y$05$EZKLCs8Ezr8rjsCpkcncRuJLVTDM2qEZrNyXJ0Z4OWNR3o.hqofyK"
      - "traefik.http.routers.prometheus.middlewares=prometheus-auth"
      - 'traefik.docker.network=production'
    networks:
      - production
      - monitoring