name: "Deploy Infra (Prometheus)"
on:
  push:
    branches:
      - main
    paths:
      - 'Infrastruture/prometheus/**'

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Copy Files"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "Infrastruture/prometheus/**"
          target: "/root/infra/prometheus"
          strip_components: 2
          rm: true
          debug: true

      - name: "Rebuild docker image"
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/infra/prometheus
            docker compose -f /root/infra/prometheus/docker-compose.yml up -d --build
