name: "Deploy Infra (Traefik)"
on:
  push:
    branches:
      - main
    paths:
      - 'Infrastruture/node_exporter/**'

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Copy Files"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "Infrastruture/node_exporter/**"
          target: "/root/infra/node_exporter"
          strip_components: 2
          rm: true
          debug: true
